dist: trusty
language: python
python:
  - "2.7"

env:
  matrix:
    - CHECK=pylint
    - CHECK=format


# command to install dependencies
install: 
  - "pip install --upgrade setuptools"
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "yum install -y npm"
  - "npm install eslint --save-dev"

# command to run tests
script:
  - export PYTHONPATH=${PWD%/*}
  - ls $PYTHONPATH
  - if [[ "${CHECK}" == "pylint"  ]];
    then travis_wait 30 .travis.d/runPylint.sh;
    elif [[ "${CHECK}" == "format" ]] && [[ "${TRAVIS_PULL_REQUEST}" != "false" ]];
    then git remote add GH https://github.com/DIRACGrid/WebAppDIRAC.git; git fetch --no-tags GH ${TRAVIS_BRANCH}; git branch -vv; git diff -U0 GH/${TRAVIS_BRANCH} | pycodestyle --diff;
    fi
  - node_modules/.bin/eslint WebApp

## ignore errors for sourcefiles "-i"
after_success:
  - if [[ "${CHECK}" == "pytest"  ]];
    then codecov;
    fi
