name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: |
        # Skiped for now: Error: HttpError: Must have admin rights to Repository
        # uses: actions/labeler@v3
        # with:
        #   repo-token: "${{ secrets.PAT }}"
