name: PR sweep

on:
  - push

jobs:
  pr-sweep:
    runs-on: ubuntu-latest
    concurrency: pr-sweep
    if: github.repository == 'DIRACGrid/WebAppDIRAC'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: DIRACGrid/pr-sweeper@main
        with:
          github-pat: ${{ secrets.PAT }}
          pr-project-name: DiracGridBot/WebAppDIRAC
